"""initial schema

Revision ID: d4b28c6514bc
Revises: 
Create Date: 2026-04-11 14:13:37.722756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b28c6514bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id')
    )
    op.create_table('org_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='supervisor', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_member')
    )
    op.create_index('ix_org_members_org_id', 'org_members', ['org_id'], unique=False)
    op.create_index('ix_org_members_user_id', 'org_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_org_status', 'projects', ['org_id', 'status'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'rut', name='uq_worker_org_rut')
    )
    op.create_index('ix_workers_org_active', 'workers', ['org_id', 'is_active'], unique=False)
    op.create_index('ix_workers_org_id', 'workers', ['org_id'], unique=False)
    op.create_index('ix_workers_org_specialty', 'workers', ['org_id', 'specialty'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=True),
    sa.Column('score_quality', sa.SmallInteger(), nullable=False),
    sa.Column('score_safety', sa.SmallInteger(), nullable=False),
    sa.Column('score_punctuality', sa.SmallInteger(), nullable=False),
    sa.Column('score_teamwork', sa.SmallInteger(), nullable=False),
    sa.Column('score_technical', sa.SmallInteger(), nullable=False),
    sa.Column('score_average', sa.Float(), nullable=False),
    sa.Column('would_rehire', sa.String(length=20), nullable=False),
    sa.Column('rehire_reason', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'worker_id', name='uq_evaluation_project_worker')
    )
    op.create_index('ix_evaluations_org_id', 'evaluations', ['org_id'], unique=False)
    op.create_index('ix_evaluations_project_id', 'evaluations', ['project_id'], unique=False)
    op.create_index('ix_evaluations_score_avg', 'evaluations', ['score_average'], unique=False)
    op.create_index('ix_evaluations_worker_id', 'evaluations', ['worker_id'], unique=False)
    op.create_table('project_workers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('role_in_project', sa.String(length=100), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'worker_id', name='uq_project_worker')
    )
    op.create_index('ix_project_workers_project_id', 'project_workers', ['project_id'], unique=False)
    op.create_index('ix_project_workers_worker_id', 'project_workers', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_workers_worker_id', table_name='project_workers')
    op.drop_index('ix_project_workers_project_id', table_name='project_workers')
    op.drop_table('project_workers')
    op.drop_index('ix_evaluations_worker_id', table_name='evaluations')
    op.drop_index('ix_evaluations_score_avg', table_name='evaluations')
    op.drop_index('ix_evaluations_project_id', table_name='evaluations')
    op.drop_index('ix_evaluations_org_id', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_workers_org_specialty', table_name='workers')
    op.drop_index('ix_workers_org_id', table_name='workers')
    op.drop_index('ix_workers_org_active', table_name='workers')
    op.drop_table('workers')
    op.drop_index('ix_projects_org_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_org_members_user_id', table_name='org_members')
    op.drop_index('ix_org_members_org_id', table_name='org_members')
    op.drop_table('org_members')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
